language: haskell

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$TRAVIS_BUILD_DIR/dist-newstyle"

matrix:
  include:
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.5

install: cabal new-update

script: cabal new-build
