language: haskell

cabal: "2.4"

cache:
  directories:
  - $HOME/.cabal/packages
  - $HOME/.cabal/store
  - $HOME/.cabal/bin
  - "$TRAVIS_BUILD_DIR/dist-newstyle"

matrix:
  include:
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.5

install: cabal new-update

script: cabal new-build
